services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: auction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6778
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auction
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 6778

volumes:
  postgres_data:
    driver: local
